name: "Next.js Changed Routes"
description:
  "A GitHub Action that outputs a list of changed routes for a commit or pull
  request."
author: "FluxCapacitor2"

branding:
  icon: "edit"
  color: "green"

# Define your inputs here.
inputs:
  separator:
    description:
      "The separator used to split the changedFiles input into an array."
    default: ","

  includedPaths:
    description:
      "Specify a list of globs to include in file tracing, separated by
      newlines. These globs should only match application code, like your `app/`
      directory and an additional `components` directory. Using more specific
      globs will increase performance and reduce the number of files that need
      to be traced."
    default: |
      src/**
      app/**
      components/**
    required: false

  pageExtensions:
    description:
      "A list of file extensions used by Next.js pages, separated by the
      specified `separator`."
    default: "js,jsx,ts,tsx"

  changedFiles:
    description:
      "A list of files that were changed as a result of the current commit or
      pull request. This should be the output of @tj-actions/changed-files."
    required: true

# Define your outputs here.
outputs:
  changedRoutes:
    description:
      "A list of changed routes for the current commit or pull request.
      Formatted as relative URL paths, joined by the separator specified in the
      `separator` input."

runs:
  using: node20
  main: dist/index.js
