name: "Next.js Changed Routes"
description:
  "A GitHub Action that outputs a list of changed routes for a commit or pull
  request."
author: "FluxCapacitor2"

branding:
  icon: "edit"
  color: "green"

# Define your inputs here.
inputs:
  changedFiles:
    description:
      "A list of files that were changed as a result of the current commit or
      pull request. This should be the output of @tj-actions/changed-files."
    required: true

# Define your outputs here.
outputs:
  changedRoutes:
    description:
      "A list of changed routes for the current commit or pull request.
      Formatted as relative URL paths."

runs:
  using: node20
  main: dist/index.js
